### ISSUE TITLE
Register時にSQLExceptionが発生する

### ISSUE THREAD

**Issue by kamadakohei** [ankokuty/HakoniwaBadStore#2]
# 環境
M1mac

# 事象

BadStore起動後、Registerボタンを押してアカウントを発行しようとすると以下のエラーが発生する

```
java.lang.RuntimeException: java.sql.SQLException: Error opening connection
	at badstore.BadStore.authuser(BadStore.java:2044)
	at badstore.BadStore.lambda$startServer$1(BadStore.java:183)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:525)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:511)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:176)
	at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:163)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:140)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:164)
```

# 原因
sqlite-jdbcがM1macに対応していないバージョンのために発生している事象と思われます。
https://stackoverflow.com/questions/70048681/java-sql-sqlexception-error-opening-connection

**Comment by ankokuty** [comment]
手元にM1 Macがないので確認出来ないのですが、sqlite-jdbcを3.34.0にしてビルドし直してみました。
こちらだとどうでしょうか？
[Hakoniwa BadStore.zip](https://github.com/ankokuty/HakoniwaBadStore/files/9135342/Hakoniwa.BadStore.zip)

**Comment by kamadakohei** [comment]
@ankokuty 
ご対応ありがとうございます。
無事エラーなくregisterできました。

**Comment by ankokuty** [comment]
確認ありがとうございます。
